// Generated by gencpp from file espbot_a/Servo_Position.msg
// DO NOT EDIT!


#ifndef ESPBOT_A_MESSAGE_SERVO_POSITION_H
#define ESPBOT_A_MESSAGE_SERVO_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace espbot_a
{
template <class ContainerAllocator>
struct Servo_Position_
{
  typedef Servo_Position_<ContainerAllocator> Type;

  Servo_Position_()
    : angle(0.0)  {
    }
  Servo_Position_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::espbot_a::Servo_Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::espbot_a::Servo_Position_<ContainerAllocator> const> ConstPtr;

}; // struct Servo_Position_

typedef ::espbot_a::Servo_Position_<std::allocator<void> > Servo_Position;

typedef boost::shared_ptr< ::espbot_a::Servo_Position > Servo_PositionPtr;
typedef boost::shared_ptr< ::espbot_a::Servo_Position const> Servo_PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::espbot_a::Servo_Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::espbot_a::Servo_Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace espbot_a

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'espbot_a': ['/home/marcin/catkin_ws/src/espbot_a/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::espbot_a::Servo_Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::espbot_a::Servo_Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::espbot_a::Servo_Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::espbot_a::Servo_Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::espbot_a::Servo_Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::espbot_a::Servo_Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::espbot_a::Servo_Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const ::espbot_a::Servo_Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4edb55038e2b8889ULL;
  static const uint64_t static_value2 = 0x76a0c0c56935341cULL;
};

template<class ContainerAllocator>
struct DataType< ::espbot_a::Servo_Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "espbot_a/Servo_Position";
  }

  static const char* value(const ::espbot_a::Servo_Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::espbot_a::Servo_Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n\
";
  }

  static const char* value(const ::espbot_a::Servo_Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::espbot_a::Servo_Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Servo_Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::espbot_a::Servo_Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::espbot_a::Servo_Position_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESPBOT_A_MESSAGE_SERVO_POSITION_H
